apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  labels:
    app: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: nagasatishdocker/spring-app:latest
        ports:
        - containerPort: 8080
        resources:
            limits:
              cpu: 500m
            requests:
               cpu: 100m
